version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./public:/app/public
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
